### ISSUE TITLE
TRACKING: Numpy 2.0 support

### ISSUE THREAD

**Issue by jeremyleung521** [westpa/westpa#372]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]  
Numpy 2.0.0 will be released June 16th 2024. It is imperative that we either pin our dependency version to <2 and/or check our code base for any potential problems before release. I assume a lot of the Cython stuff will need to be checked too.

Release Notes and Migration Guide:
https://numpy.org/devdocs/release/2.0.0-notes.html
https://numpy.org/devdocs/numpy_2_0_migration_guide.html

**Describe the solution you'd like.** A clear and concise description of what you want to happen.  
- [x] Pin dependency to < 2 before it's released
- [x] Check whether the multitude of breaking changes affects us
- [x] If 2.0 compatible, remove the dependency pin.

**Describe alternatives you've considered.** A clear and concise description of any alternative solutions or features you've considered.  

**Additional context.** Add any other context or screenshots about the feature request here.

**Comment by synapticarbors** [comment]
An easy way to see what changes need to be made would be to apply the ruff plugin and then check the diff:
https://numpy.org/devdocs/numpy_2_0_migration_guide.html#ruff-plugin

It might be a good starting point to see how extensively WESTPA relies on deprecated apis.

**Comment by jeremyleung521** [comment]
Another related issue with `numpy2` is that `oldest-supported-numpy` is now deprecated (which is great since functionality is now in numpy>=1.25) but we will also have to build with `numpy2` for support with 1.XX and 2.XX.  None of the numpy >= 1.25 are released for python 3.7/3.8. I'll deal with this in a separate PR from #374.

We could also consider dropping python 3.7/3.8 support.

https://github.com/scipy/oldest-supported-numpy
https://github.com/numpy/numpy/issues/24300

**Comment by jeremyleung521** [comment]
Just a small update to this issue. We've pinned to `numpy<2` in `v2022.07`. We will release `v2022.10` with `numpy >= 2` support in the near future.

**Comment by jeremyleung521** [comment]
Update: June 16th is the planned release date.
https://github.com/numpy/numpy/issues/24300#issuecomment-2125643448

**Comment by jeremyleung521** [comment]
Still waiting for MDTraj to support numpy2. Getting real close on that front, I think.

**Comment by jeremyleung521** [comment]
PR is finished. Hoping to release in the next couple weeks after review.

**Comment by jeremyleung521** [comment]
Merged in. Will be released as part of 2022.12

**Comment by jeremyleung521** [comment]
There are some weirdness/difference between numpy1 and numpy2 bin_topology pickles, which warrants some double-checking. delaying the release a little bit as i investigate.

https://github.com/jeremyleung521/westpa/actions/runs/13338955695/job/37260046060

**Comment by jeremyleung521** [comment]
Part of v2022.12.
